### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by escamoteur** [comment]
Hi, sorry I saw the PR just yet and I already made change while fixing another bug which will create a merge conflict with your latest commit at least on the null safety branch. could you revert that last commit?

**Comment by escamoteur** [comment]
Why closing? Then I will copy over your other changes manually

**Comment by ghost** [comment]
Thomas, I'm sorry.
I thought that's what you asked about.
I don't know how to revert commit at PR.

**Comment by escamoteur** [comment]
I think if you revert the last commit on your repo it should also vanish from the PR

**Comment by ghost** [comment]
Thomas, there is no way to do that.
I already deleted my fork for the PR.
I'm sorry for bothering you.
*
Have a great weekend!

**Comment by escamoteur** [comment]
you didn't bothr me, I'm just sad because of all your work. I will try to merge your fixes manually

**Pull request closed without merging**
