### PR TITLE
Fixed unnecessary_non_null_assertion. Upgraded packages. Removed unnecessary imports.

### PR DESCRIPTION
**Pull request by Ruzo**
There is still a warning about 'author' field in pubspec because it's deprecated (https://github.com/dart-lang/site-www/issues/2029#issuecomment-566529592)

### CODE REVIEW

**Comment by esDotDev** [comment]
@escamoteur can you land this when you have some time?

**Comment by escamoteur** [comment]
Hi, sorry for the long time to respond for me, but I had to struggle with my mental health for the last 7 months.
Maybe @esDotDev would like to get a co-maintainer of my get_it packages in case I'm not available?

@Ruzo what line length are you using in your editor? Unfortunately, the whole source got reformated so I don't see what was changed.

**Comment by Ruzo** [comment]
> Hi, sorry for the long time to respond for me, but I had to struggle with my mental health for the last 7 months. Maybe @esDotDev would like to get a co-maintainer of my get_it packages in case I'm not available?
> 
> @Ruzo what line length are you using in your editor? Unfortunately, the whole source got reformated so I don't see what was changed.

Oops, sorry about that. Did not know it could become an issue. I did set it to 120 while trying to make use of my Ultrawide monitor. Will set it back to 80. I can re-submit if you want?

**Comment by escamoteur** [comment]
That would be fine, thanks
Am 4. Feb. 2022, 16:17 +0100 schrieb Richard Rouzeau ***@***.***>:

**Comment by Ruzo** [comment]
Alright. Do you want to do something about that pubspec.yaml error?
```
The 'author' field is no longer used and can be removed.
Try removing the field.
```

**Comment by escamoteur** [comment]
Nope. call it spite, but I'm still not happy that they removed that field without adding a replacement :-)

**Comment by Ruzo** [comment]
:-) By the way, the get_it_mixin_stateful_test.dart is not passing right now. Is that okay?

```shell
00:03 +17: allReady async object that is not finished at the start                                                                                                                                                                                                                                 
Not yet ready objects:
[Object asyncObject2 has not completed]
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: <null>
  Actual: 'Ready'

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///Users/richardrouzeau/apps/Flutter/get_it_mixin/test/get_it_mixin_stateful_test.dart:506:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///Users/richardrouzeau/apps/Flutter/get_it_mixin/test/get_it_mixin_stateful_test.dart line 506
The test description was:
  allReady async object that is not finished at the start
════════════════════════════════════════════════════════════════════════════════════════════════════
00:03 +17 -1: allReady async object that is not finished at the start [E]                                                                                                                                                                                                                          
  Test failed. See exception logs above.
  The test description was: allReady async object that is not finished at the start
  
00:03 +18 -1: isReady async object that is not finished at the start                                                                                                                                                                                                                               
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: <null>
  Actual: 'Ready'

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///Users/richardrouzeau/apps/Flutter/get_it_mixin/test/get_it_mixin_stateful_test.dart:553:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///Users/richardrouzeau/apps/Flutter/get_it_mixin/test/get_it_mixin_stateful_test.dart line 553
The test description was:
  isReady async object that is not finished at the start
════════════════════════════════════════════════════════════════════════════════════════════════════
00:03 +18 -2: isReady async object that is not finished at the start [E]                                                                                                                                                                                                                           
  Test failed. See exception logs above.
  The test description was: isReady async object that is not finished at the start
  
00:03 +18 -2: Some tests failed.
```

**Comment by esDotDev** [comment]
> Hi, sorry for the long time to respond for me, but I had to struggle with my mental health for the last 7 months. Maybe @esDotDev would like to get a co-maintainer of my get_it packages in case I'm not available?
> 
> @Ruzo what line length are you using in your editor? Unfortunately, the whole source got reformated so I don't see what was changed.

Hey Thomas, sorry to hear about that, I hope you are doing ok these days and things are looking more sunny :) 

I'm happy to help maintain the lib, but I'm quite busy right now, and so far have just been a user of your library without ever diving into the src, so it will likely be some time before I can contribute anything useful or fully get up to speed.

**Comment by escamoteur** [comment]
@esDotDev I add you as maintainer so that you get informed about new issues. I just want to make sure that someone has an eye on it because I can't guarantee how well I will be in the future and many people rely on the package.
Feeling much better at the moment, thanks so much for helping

**Comment by esDotDev** [comment]
Any time my friend, let me know what I can do to help.

**Comment by Ruzo** [comment]
Okay, this is not working. I'm going to have to submit a completely new one in order to fix the line length issue without having changes all over the files.

**Review by esDotDev — APPROVED** [review]
@escamoteur this LGTM, thoughts?

Un-related, but looks like we have some nice tests made, but they are not integrated into github.com. Maybe I'll take a stab at wiring that up this week?

**Comment by esDotDev** [comment]
> Nope. call it spite, but I'm still not happy that they removed that field without adding a replacement :-)

@escamoteur if we're going to keep it in, lets make it right :D 
image

**Pull request merged**
